server:
  port: 8084
spring:
  application:
    name: page-service
  thymeleaf:
    cache: false
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: 192.168.0.105
    username: leyou
    password: leyou
    virtual-host: /leyou
eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.105:10086/eureka