server:
  port: 9000

#该服务名称
spring:
  application:
    name: api-gateway

#注册中心
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://admin:vsj555@localhost:8761/eureka/

#自定义路由映射
zuul:
  routes:
    order-service: /order/**
    admin-service: /admin/**
  #统一入口为上面的配置，其他入口忽略
  ignored-patterns: /*-service/**
  #处理http请求头为空的问题
  sensitive-headers: