server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yun6
    username: root
    password: root
  rabbitmq:
    host: 192.168.0.105      #127.0.0.1
    username: leyou
    password: leyou
    virtual-host: /leyou
    template: #有关`AmqpTemplate`的配置
      retry:  #失败重试
        enabled: true   #开启失败重试
        initial-interval: 10000ms  #第一次重试的间隔时长
        max-interval: 80000ms   #最长重试间隔，超过这个间隔将不再重试
        multiplier: 2   #下次重试间隔的倍数，此处是2即下次重试间隔是上次的2倍
      exchange: ly.item.exchange
    publisher-confirms: true   #生产者确认机制，确保消息会正确发送，如果发送失败会有错误回执，从而触发重试
eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.105:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 192.168.0.105
mybatis: #能看到sql语句的配置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl